### ISSUE TITLE
RHVoice - Home Assistant - MQTT

### ISSUE THREAD

**Issue by fuzzznet** [definitio/ha-rhvoice#10]
Hey!
You've done a great integration!
Is it possible to send the generated 123.mp3 directly to the MQTT broker,
instead of media_player.main?
I have an ESP MQTT player (https://github.com/schmurtzm/MrDiy-Audio-Notifier), 
which can play mp3 from anywhere, not only within a local network!
Could you follow the submission rate of MQTT?

**Comment by definitio** [comment]
There is no MQTT player integration in Home Assistant but you can use RHVoice without this integration. Just run `rhvoice-rest` container - [step 1](https://github.com/definitio/ha-rhvoice#installation) and then publish `http://<server hostname or IP address>/say?format=mp3&volume=50&pitch=50&voice=anna&rate=40&text=test` to an ESP MQTT player.

**Comment by fuzzznet** [comment]
=) I know, that's why I turned to you.
Perhaps as part of the RHVoice - HA integration, you can add the submit capability to MQTT? ESP as a player is a very promising thing for notifications.

**Comment by definitio** [comment]
How you want to use it? Call service, use GUI? May be there is other solution. TTS integrations can't send anything to clients, they just returns output to Home Assistant.

**Comment by fuzzznet** [comment]
TTS integrations can return integration with a known name, so that when the name.mp3 file appears, the home assistant can redirect to topik in MQTT?

**Comment by definitio** [comment]
You need another integration that will request audio file and then send it to MQTT. It looks like over engineering. Why you want to use two integrations instead of `MQTT Publish service` ? It can be called from UI too with [mini-media-player card](https://github.com/kalkih/mini-media-player).
