### ISSUE TITLE
Не запускается контейнер с rhvoice

### ISSUE THREAD

**Issue by vladislavmvv** [definitio/ha-rhvoice#11]
HA на Rasspberry Pi 4B, установлен Mopidy, через google_translate синтез работает. Пытаюсь запустить контейнер с rhvoice, но он не запускается. Запускал командой "docker run -d -p 8080:8080 aculeasis/rhvoice-rest:arm32v7", контейнер создался, но не работает. В логе:

Setting trap PID 1
Fatal Python error: pyinit_main: can't initialize time
Python runtime state: core initialized
PermissionError: [Errno 1] Operation not permitted
Current thread 0xb6f31460 (most recent call first):
<no Python frame>

**Comment by definitio** [comment]
arm64v8 не пробовали?

**Comment by vladislavmvv** [comment]
> arm64v8 не пробовали?

Тоже создается, но запустить не получается. И предупреждение в консоли: "WARNING: The requested image's platform (linux/arm64/v8) does not match the detected host platform (linux/arm/v7) and no specific platform was requested"

**Comment by definitio** [comment]
Попробуйте обновить `libseccomp2`:
```
wget ftp.us.debian.org/debian/pool/main/libs/libseccomp/libseccomp2_2.5.3-2_armhf.deb
sudo dpkg -i libseccomp2_2.5.3-2_armhf.deb
```
P.S.: используйте arm32v7

**Comment by vladislavmvv** [comment]
> Попробуйте обновить `libseccomp2`:
> 
> ```
> wget ftp.us.debian.org/debian/pool/main/libs/libseccomp/libseccomp2_2.5.3-2_armhf.deb
> sudo dpkg -i libseccomp2_2.5.3-2_armhf.deb
> ```
> 
> P.S.: используйте arm32v7

Запустился, работает! После перезагрузки хоста стал остановленным, запустил вручную, пока работает. Спасибо за помощь!

**Comment by vladislavmvv** [comment]
И запускать надо командой:
sudo docker run --restart=always -d -p 8080:8080 aculeasis/rhvoice-rest:arm32v7
