### ISSUE TITLE
unsupported 

### ISSUE THREAD

**Issue by znack14** [definitio/ha-rhvoice#12]
Hello.  Great integration, love it, but Supervised is fighting about an unsupported container.  Can this be fixed?

**Comment by definitio** [comment]
Unfortunately, HA devs don't like third party containers. There is only way to fix it - create an add-on, but I don't have time to do it.

**Comment by znack14** [comment]
дуже шкода. Працює справно, от тільки може нашкодити, якщо розробники НА щось поміняють

**Comment by znack14** [comment]
> Unfortunately, HA devs don't like third party containers. There is only way to fix it - create an add-on, but I don't have time to do it.
Hello.  Perhaps some donations or something else could persuade you to make an application that would be supported in HAOs.  I really want to use a local voice instead of a cloud one.  Please think.

**Comment by znack14** [comment]
> Unfortunately, HA devs don't like third party containers. There is only way to fix it - create an add-on, but I don't have time to do it.

Hello.  Perhaps some donations or something else could persuade you to make an application that would be supported in HAOs.  I really want to use a local voice instead of a cloud one.  Please think.

**Comment by definitio** [comment]
I'll look into it.

**Comment by znack14** [comment]
> Я посмотрю на это.

Good day!!!  Any success with RHVoice for HAOs?  And by the way, I don't know how to send you donations.  Please indicate the kurta or bill

**Comment by definitio** [comment]
@znack14 Hi, can you test the [addon](https://github.com/definitio/ha-rhvoice-addon)? For now only aarch64 and amd64 supported.

Donations are always welcome and very much appreciated! Unfortunately most payment services don't work in my country. I have added my bitcoin address to readme: `bc1qd6khey9xkss6vgd6fqpqdyq4lehtepajkcf256`.

**Comment by znack14** [comment]
> @znack14Привет, можешь протестировать [аддон](https://github.com/definitio/ha-rhvoice-addon) ? На данный момент поддерживаются только aarch64 и amd64.
> 
> Пожертвования всегда приветствуются и очень ценятся! К сожалению, большинство платежных сервисов не работают в моей стране. Я добавил свой биткойн-адрес в файл readme: `bc1qd6khey9xkss6vgd6fqpqdyq4lehtepajkcf256`.

Hello.  Everything works, very cool.  Thank you very much.  I will try it with a bitcoin wallet today, because it is the first time for me.  But I will definitely manage.  Thank you again.
