### ISSUE TITLE
Недоговаривание

### ISSUE THREAD

**Issue by booroondook-eng** [definitio/ha-rhvoice#2]
Столкнулся с проблемой "недоговаривания". То есть, заданная фраза проговаривается не до конца, а обрезается за полслова-слово до конца. Временно выхожу из положения, добавляя в конец каждой задаваемой фразы "мусор" из 4-5 согласных. Например "Доброе утро! ввввв".
Конфигурация такая: Home Assistant установлен на PC с Ubuntu 20.04. В качестве аудиоплеера используется MPD на другом компьютере (Raspberry Pi).
Сначала я грешил на то, что фраза формируется (т.е., TTS-озвучивается) не полностью. Но оказалось, что это не так - сгенерированные MP3-файлы содержат полные фразы и на PC под Windows воспроизводятся полностью.
Потом я решил, что проблема в MPD. Однако, сторонние MP3-файлы там воспроизводятся нормально и до конца. Думал, что проблема вызвана неполным скачиванием файла через http(s). Однако файл скачивается полностью.
И вот, что оказалось. Если сгенерированный файл просто взять из папки Home Assistant'а и "скормить" в MPD вручную, то он тоже воспроизводится не до конца! Получается, что проблема в особенностях генератора MP3, используемого в RHVoice - то ли какие-то нарушения формата MP3, то ли не тот кодек, то ли еще что-то.
В-общем, надо бы как-то решить эту проблему.

**Comment by definitio** [comment]
Не могу воспроизвести проблему у себя. Возможно стоит попробовать другой плеер (я использую Mopidy c плагином mopidy-mpd). Несколько лет назад у меня были какие-то проблемы (уже не помню) с MPD, поэтому я отказался от его использования. Загрузите mp3 куда-нибудь - хочу проверить.

**Comment by booroondook-eng** [comment]
Да с настройкой плеера была куча проблем из-за попыток правильно сконфигурировать ALSA и/или Pulseaudio. По крайней мере, на том же хосте, что и HA, заставить MPD звучать не удалось - подозреваю, что из-за сопутствующих "ассистенту" контейнеров Docker, где запускается pulseaudio. И вот с десятой, наверное, попытки "брожения" между линуксовыми компами удалось запустить mpd через alsa на Raspberry Pi (и то - благодаря тому, что в raspi-config есть опция выбора звуковой карты по умолчанию).
Файликом охотно делюсь. Записанная фраза такая: "Раз, два, три! Говорим-по-русски! И не глотаем слова!"
Если его запустить на ПК, то все ОК. А если под MPD (через mpc) - неважно, как - автоматом от HA или вручную из командной строки (причем, не с http, а уже заранее скопированный в локальную папку и даже переименованный для краткости), то обрывает на "...глотае"
[rhvoice.zip](https://github.com/definitio/ha-rhvoice/files/5378311/rhvoice.zip)

**Comment by definitio** [comment]
Воспроизвелось корректно через Mopidy, так что похоже все таки проблема в MPD.

**Comment by booroondook-eng** [comment]
А можно мне попросить у вас, так сказать, "в обратку" какой-нибудь из сгенерированных у вас файлов? Попробую скормить его через http и напрямую.

**Comment by definitio** [comment]
Конечно: [audio.zip](https://github.com/definitio/ha-rhvoice/files/5378880/audio.zip)
Заканчивается на "1, 2, 3".

**Comment by booroondook-eng** [comment]
В первый раз оборвалось после "два". Во второй и последующие - после "один".
Скармливал локальный файл - т.е., положил его в /var/lib/mpd (и переименовал в test.mp3), а затем последовательно:
mpc clear
mpc add test.mp3
mpc play
mpc play
mpc play
и т.д.

**Comment by definitio** [comment]
Ожидаемо. Я все таки рекомендую Mopidy с MPD-плагином. Они совместимы с MPD, так что со стороны клиентов изменений настроек не требуется.

**Comment by booroondook-eng** [comment]
Спасибо, попробую.
P.S. Еще бы вопрос с ударениями решить. Вроде бы в RHVoice они есть, но для этого надо опции прописывать в конфиг-файл. А до конфиг-файла не добраться, т.к. он внутри докер-контейнера.

**Comment by definitio** [comment]
Попробуйте примонтировать в контейнер файл конфигурации в `/usr/local/etc/RHVoice/RHVoice.conf`.

**Comment by booroondook-eng** [comment]
Попробую. Правда, пока не знаю, как это делается, но быстро научусь :-)

**Comment by definitio** [comment]
Как успехи?

**Comment by booroondook-eng** [comment]
Примонтировал (заодно научился, как это делать - через Portainer оказалось совсем просто).
Но результат печальный - такое ощущение, что конфиг-файл не воспринимается при генерации файла.
Единственное, что получилось - это прописывание в один из словарей (/usr/local/etc/RHVoice/dicts/Russian/*.txt) нужного произношения конкретного слова с указанием ударения значком "+".
Но вот "в динамике" - т.е., при создании сообщения в Хоум-Асисстенте - постановка "+" в текст приводит к тому, что в сгенерированном файле диктор этот самый "+" произносит как "плюс".
Например, запись "температ+ура" будет озвучена как "температ-плюс-ура".

P.S. Да, а с недоговариванием я уже смирился - как и писал выше, просто ставлю после фразы несколько пробелов и 5-6 согласных букв - например, "       ввввв". И получается, что не договаривается только этот "хвост", а основная фраза произносится полностью.

**Comment by booroondook-eng** [comment]
Я уж не стану новую тему открывать - буду писать пока в эту. Проявился забавный глюк. Вдруг, ни с того, ни с сего, перестал говорить речевой информатор при запуске из сценариев и автоматизаций. Но при этом заданный вруную текст на карточке плеера (у меня используется MPD, установленный на другом компьютере)  прекрасно произносится.
Пошел смотреть в консоль плеера, и вижу:
`ERROR: Failed to decode https://192.168.0.12:8123/api/tts_proxy/4fccb959ba88d2da14c3f45a4d799f105a9d2b93_ru-ru_-_rhvoice.mp3; CURL failed: SSL: certificate subject name (***.*****.ru) does not match target host name '192.168.0.12'`
То есть, получается, что HA сообщает в MPD ссылку, содержащую не доменное имя HA-хоста, а его IP-адрес во внутренней сети. При этом используется протокол https, который ругается на то, что сертификат сервера выписан не на этот IP-адрес, а на доменное имя такое-то. Поэтому файл не скачивается и соответственно не включается в очередь и в итоге не воспроизводится. Я начинаю вспоминать, что я в последнее время менял в конфигурации HA. И вспоминаю - я удалил "base_url" из configuration.yaml (интеграция "http"). А удалил я его оттуда, потому что так мне "посоветовала" запись в логе HA:
`2020-11-03 21:01:37 WARNING (MainThread) [homeassistant.components.http] The 'base_url' option is deprecated, please remove it from your configuration` 
В-общем, пока вернул "base_url" на место, и информатор снова заговорил.
Но вообще надо с этим что-то делать.

**Comment by definitio** [comment]
Вот так должно быть:
```yaml
tts:
  - platform: rhvoice
    base_url: http://192.168.0.12:8123
    ...
```
Это описано в [документации Home Assistant](https://www.home-assistant.io/integrations/tts/).
P.S.: Вообще разные проблемы должны быть в разных issues.

**Comment by booroondook-eng** [comment]
Поправочка: надо указывать не локальный адрес, а публичный (адрес или доменное имя).
Тогда работает.
Насколько я понимаю, "base_url" используется для формирования ссылки для скачивания аудиофайла с сервера HA на сервер медиаплеера. И если используется https, то проверяется достоверность сертификата. Поэтому "base_url" должен соответствовать сертификату, который, как правило, прикреплен именно к публичному доменному имени сервера HA, а не к его адресу в локальной сети.

Спасибо!

**Comment by frederickjh** [comment]
I am also hearing the audio being cut off but this is only with an experimental Android client called [M.A.L.P. - Android MPD client](https://gitlab.com/gateship-one/malp), so this can be excused for now since it is in the beginning stages of development.

I have to wonder if @booroondookZ is using the most recent version of `mpd`.  On one computer that is not cutting TTS audio off I am running Music Player Daemon 0.19.12. The most recent version is **0.22.3**. I believe many Linux distros have older versions in their Repositories. They do say that they are constantly fixing bugs and to check if you still have the issue on the newest version before submitting a bug report.

**Comment by booroondook-eng** [comment]
I use MPD 0.21.5 on Raspbian 10 on Raspberry Pi 3B
UPD. The problem disappeared after upgrade MPD to 0.22.3. Thank you **frederickjh**!

**Comment by frederickjh** [comment]
You are welcome @booroondookZ!  Good to hear you got it working. In that case then this issue can be closed, as this is not an issue with **ha-rhvoice**.
