### ISSUE TITLE
RHVoice in Home Assistant

### ISSUE THREAD

**Issue by kapniksuper** [definitio/ha-rhvoice#5]
1. rhvoice-rest Docker container установлен.
2. В браузере через "http://192.168.1.250:8080/say?text=123" все работает - произносит "сто двадцать три"

Как пользоваться в Home Assistant?
В configuration.yaml:
tts:
  - platform: rhvoice
    voice: anna
    host: <192.168.1.250>

Но если пробовать Developer Tools - Call Service tts.rhvoice_say c параметром Привет, то возвращает ошибку ""Failed to call service tts/rhvoice_say. expected dict for dictionary value @ data['service_data']. Got 'Привет'""

**Comment by definitio** [comment]
Сервис вызываете с такими параметрами:
```
message: Привет
entity_id: media_player.<player_name>
```
?

**Comment by kapniksuper** [comment]
С такими параметрами сервис вызывается без ощибок, но звука нет все равно.
В логах:
Logger: custom_components.rhvoice.tts
Source: custom_components/rhvoice/tts.py:133
Integration: rhvoice (documentation, issues)
First occurred: 8:20:40 PM (1 occurrences)
Last logged: 8:20:40 PM

Timeout for RHVoice API

**Comment by definitio** [comment]
В configuration.yaml кавычек нет:
```
tts:
  - platform: rhvoice
    voice: anna
    host: 192.168.1.250
```
?

**Comment by kapniksuper** [comment]
Да, действительно, пропустил кавычки в адресе.
