### ISSUE TITLE
Hard coded http:// does not allow using https:// with Text to Speech (tts) Say Service

### ISSUE THREAD

**Issue by frederickjh** [definitio/ha-rhvoice#6]
I have my Home Assistant setup to use a public domain name using an SSL certificate. Sending TTS notifications to the Home Assistant Android app works.

What does not work is using the TTS Say service. If I try to send these either using the Developer Tools > Services

![image](https://user-images.githubusercontent.com/864159/103835467-a7716b80-5086-11eb-8edd-deccec2872f7.png)

or via the popup from clicking on the three dots in a media player in lovelace

![image](https://user-images.githubusercontent.com/864159/103835730-51e98e80-5087-11eb-8d1c-f4c8455a5c88.png)

![image](https://user-images.githubusercontent.com/864159/103835749-5dd55080-5087-11eb-9d04-406024f2aac4.png)

I get errors like these in the log:

```python
 2021-01-07 00:33:41 ERROR (MainThread) [custom_components.rhvoice.tts] Error 400 on load URL http://example.com:8880/say?text=When+pigs+can+fly!&voice=alan&format=mp3&rate=50&pitch=50&volume=100
 2021-01-07 00:33:41 ERROR (MainThread) [homeassistant.components.tts] Error on init TTS: No TTS from rhvoice for 'When pigs can fly!'
```

In tts.py on [line 79](https://github.com/definitio/ha-rhvoice/blob/1d0bf664523bf723ef3412de6702b36d69346b37/custom_components/rhvoice/tts.py#L79) the **http** is hard coded:

```python
        self._url = f'http://{conf.get(CONF_HOST)}:{conf.get(CONF_PORT)}/say'
```
If I change the **http** to **https**  on line 79 of `tts.py`, clear the TTS cache and restart Home Assistant,  then I can use the TTS say service in Home Assistant.

```python
        self._url = f'https://{conf.get(CONF_HOST)}:{conf.get(CONF_PORT)}/say'
```

Is there a way to get the protocol from Home Assistant? I see that the host and port are brought in from Home Assistant. Maybe you can get the protocol (http or https) too.

Thanks for looking in to this!
Frederick

**Comment by definitio** [comment]
I will add option to enable ssl on weekends.

**Comment by definitio** [comment]
A new version has been released.

**Comment by frederickjh** [comment]
I installed the new version. After adding the `ssl: true` to my `configuration.yaml` and restarting rhvoice_say is working via an SSL connection. Good work!  👍
