### ISSUE TITLE
Произношение десятичного разделителя.

### ISSUE THREAD

**Issue by booroondook-eng** [definitio/ha-rhvoice#7]
В Home Assistant в качестве разделителя целой и дробной частей числа испльзуется точка ("американский" стандарт), и при произношении такого числа эта точка "проглатывается".
Например, текст "температура поднялась выше 2.4 градуса" звучит как "...двух четыре градуса".
Если же используется разделитель по "российскому" стандарту - т.е., запятая, то всё нормально: фраза "...2,4 градуса" звучит как "...двух целых и четырёх десятых градуса".
Соответственно, встает дилемма - либо 
1) заставить Home Assistant выдавать числа (значения переменных) с запятой в качестве десятичного разделителя.
...либо
2) научить RHVoice интерпретировать точку внутри числа как десятичный разделитель.

**Comment by definitio** [comment]
Используйте шаблоны:
```yaml
Температура {{ states('sensor.outside_temperature')|replace('.',',') }}°C
```

**Comment by definitio** [comment]
Проблема должна быть решена на уровне [Home Assistant](https://github.com/home-assistant/core) или [RHVoice](https://github.com/RHVoice/RHVoice). Данная интеграция вносить изменения в текст не будет, это не ее задача.
