### ISSUE TITLE
Supervisor reports that image is not supported.

### ISSUE THREAD

**Issue by booroondook-eng** [definitio/ha-rhvoice#8]
Please see a fragment from Supervisor's log:
`21-10-30 11:52:51 WARNING (MainThread) [supervisor.resolution.evaluations.base] Found images: {'portainer/portainer', 'rhvoice-rest'} which are not supported, remove these from the host! (more-info: https://www.home-assistant.io/more-info/unsupported/software)`

**Comment by definitio** [comment]
That's not an issue with rhvoice integration. Use different installation method or other docker host to run unsupported containers.

**Comment by booroondook-eng** [comment]
What is "different installation method"? Where can I read about it?

**Comment by definitio** [comment]
https://www.home-assistant.io/installation/

**Comment by booroondook-eng** [comment]
!

**Comment by definitio** [comment]
RHVoice Home Assistant add-on: https://github.com/definitio/ha-rhvoice-addon (work in progress).
